execute pathogen#infect()

syntax on
filetype plugin indent on

color molokai

set smartcase " As soon as a upper case is typed, don't ignore the case anymore

" Menu modes
set wildmode=list:longest,full
set wildmenu

set ignorecase " Ignore case when searching
set smartcase " As soon as a upper case is typed, don't ignore the case anymore
set cursorline
set incsearch
set hls
set nocompatible
nnoremap ; :

set statusline=%<%f\ %h%m%r%h%w\%y[%{&ff}]\ %{strftime(\"%c\",getftime(expand(\"%:p\")))}%=\ %l/%L\ %P
set laststatus=2

inoremap <C-b> <Left>
inoremap <C-f> <Right>
inoremap <C-e> <End>
inoremap <C-a> <Home>

" no error bell
set noeb


if has("gui_running")
	if has("gui_macvim")
		set guifont=Menlo\ Regular:h14"
	else
		set guifont=Meslo\ LG\ S\ 12
	endif
endif


noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
